### PR TITLE
Add support for AI.DAGRUN AI.DAGRUN_RO

### PR DESCRIPTION
**Pull request by dengliming**
for [https://github.com/RedisAI/redisai-go/issues/3](https://github.com/RedisAI/redisai-go/issues/3) and [https://github.com/RedisAI/redisai-go/issues/2](https://github.com/RedisAI/redisai-go/issues/2)

### CODE REVIEW

**Comment by filipecosta90** [comment]
hi there @dengliming, thanks for pushing this forward. 
I believe that we should make the way with interface with the commands supported by the dag, in the same manner we deal with them on the client. Meaning that the look and feel of a TensorSet in the dag has to be equal to the look and feel on a normal command. 
With that in mind what do you think about using a `DagCommandInterface` as last argument of the `DagRun(loadKeys []string, persistKeys []string, commands []string)` and `DagRunRO(loadKeys []string, commands []string)` instead of `commands []string`. 
Following that, we would have a Dag interface and corresponding Dag structure ( that implements the tensorget,tensorset,and modelrun), defined as follow:

```

// DagCommandInterface is an interface that represents the skeleton of DAG supported commands
// needed to map it to a RedisAI DAGRUN and DAGURN_RO commands
type DagCommandInterface interface {
	TensorSet(keyName, dt string, dims []int, data interface{}) DagCommandInterface
	TensorGet(name, format string) DagCommandInterface
	ModelRun(name string, inputTensorNames, outputTensorNames []string) DagCommandInterface
	FlatArgs() (redis.Args, error)
	GetReply(commandPosition int) (interface{}, error)
	GetReplies() ([]interface{}, []error)
}

type Dag struct {
	commands []redis.Args
}

func NewDag() *Dag {
	return &Dag{
		commands: make([]redis.Args,0),
	}
}

func (d* Dag) TensorSet(keyName, dt string, dims []int, data interface{}) *Dag {
	panic("implement me")
}

func (d* Dag) TensorGet(name, format string) *Dag {
	panic("implement me")
}

func (d* Dag) ModelRun(name string, inputTensorNames, outputTensorNames []string) *Dag {
	panic("implement me")
}

func (d* Dag) FlatArgs() (redis.Args, error) {
	panic("implement me")
}

func (d* Dag) GetReply(commandPosition int) (interface{}, error) {
	panic("implement me")
}

func (d* Dag) GetReplies() ([]interface{}, []error) {
	panic("implement me")
}

```

We would then basically call FlatArgs() to generate the args for the command, and either GetReply or  GetReplies to handle the response. 
@itamarhaber can we pick your brain on this? =) what do you guys think @itamarhaber and @dengliming ?

**Comment by dengliming** [comment]
@filipecosta90 It looks great. 👍 I will do it in this pr later.

**Comment by dengliming** [comment]
```
func (d* Dag) GetReply(commandPosition int) (interface{}, error) {
	panic("implement me")
}

func (d* Dag) GetReplies() ([]interface{}, []error) {
	panic("implement me")
}
```
@filipecosta90 I'm also has a little confused here. If we want handle the response here. we should give an reply as param for  these methods. I noticed that method `GetReplies` has no param, So we should keep response on Dag struct?

**Comment by filipecosta90** [comment]
> ```
> func (d* Dag) GetReply(commandPosition int) (interface{}, error) {
> 	panic("implement me")
> }
> 
> func (d* Dag) GetReplies() ([]interface{}, []error) {
> 	panic("implement me")
> }
> ```
> 
> @filipecosta90 I'm also has a little confused here. If we want to handle the response here. we should give an reply as param for these methods. I noticed that method `GetReplies` has no param, So we should keep response on Dag struct?

you're totally right @dengliming - forgot about i =). we need to either keep the responses on the dag structure orr receive them as input. Not sure which.  @itamarhaber what do you think should be the best approach?

**Comment by itamarhaber** [comment]
eh, I'm not sure but I would say inside the dag struct,

**Comment by filipecosta90** [comment]
> eh, I'm not sure but I would say inside the dag struct.

:+1: 
@dengliming agree? If yes, than it's consensual =)

**Comment by dengliming** [comment]
Mybe we can just return the result in `DagRun` and `DagRunRO`, no need to call `GetReply`, What do you think? @filipecosta90

**Comment by filipecosta90** [comment]
> Mybe we can just return the result in `DagRun` and `DagRunRO`, no need to call `GetReply`, What do you think? @filipecosta90 I submit the changes, you can review later.

Agree. in that sense we're able to work both the pipeline and non-pipeline in the same manner :+1:

**Comment by dengliming** [comment]
@filipecosta90 Changes have been submitted. Please review these changes if there is anything that needs to be modified.

**Comment by filipecosta90** [comment]
> @filipecosta90 Changes have been submitted. Please review these changes if there is anything that needs to be modified.

Thank for the impressive contribution @dengliming. LGTM =). @itamarhaber can you review it as well?

**Pull request merged**
